services:
  photon:
    image: rtuszik/photon-docker:latest
    container_name: photon
    restart: unless-stopped
    environment:
      - REGION=europe
      - UPDATE_STRATEGY=DISABLED
      - INITIAL_DOWNLOAD=FALSE
      - UPDATE_INTERVAL=720h
    volumes:
      - photon_data:/photon/data
    ports:
      - "2322:2322"

volumes:
  photon_data:
